// Test Data that will be removed after API integration

const pData = [
  {
    id: 10101,
    user_id: 1010,
    hotel_id: 2011,
    trip_location: 'Minden, Louisiana',
    plan_name: 'Boring Getaway',
    plan_notes: 'Visit the tiny Museum if it happens to be open.',
    activities: [
      'Tiny Museum',
      'Flooded ponds',
      'fast food',
      'Depressing Tree-less park',
    ],
  },
  {
    id: 10102,
    user_id: 1020,
    hotel_id: 2021,
    trip_location: 'New Orleans, Louisiana',
    plan_name: 'Laissez Les Bons Temps Rouler!',
    plan_notes: 'Food Tour.',
    activities: [
      'French Quarter',
      'Live jazz',
      'Jackson Square',
      'Creole Cuisine',
    ],
  },
  {
    id: 10103,
    user_id: 1030,
    hotel_id: 2031,
    trip_location: 'New York City, USA',
    plan_name: 'North',
    plan_notes: 'Fuhgeddaboudit',
    activities: [
      'Broadway',
      'Central Park',
      'Times Square',
      'Statue of Liberty',
    ],
  },
  {
    id: 10104,
    user_id: 1040,
    hotel_id: 2041,
    trip_location: 'Las Vegas, Nevada',
    plan_name: 'High Stakes Adventure',
    plan_notes: 'Try not to lose all your money.',
    activities: [
      'Casinos',
      'Shows',
      'The Strip',
      'Helicopter Tour',
      'Bellagio Fountains',
      'Red Rock Canyon',
    ],
  },
  {
    id: 10105,
    user_id: 1050,
    hotel_id: 2051,
    trip_location: 'Miami, Florida',
    plan_name: 'Sun and Fun',
    plan_notes: "Don't forget sunscreen.",
    activities: [
      'South Beach',
      'Art Deco District',
      'Ocean Drive',
      'Boat Tour',
      'Little Havana',
      'Wynwood Walls',
      'Vizcaya Museum and Gardens',
      'Miami Seaquarium',
    ],
  },
  {
    id: 10106,
    user_id: 1060,
    hotel_id: 2061,
    trip_location: 'San Francisco, California',
    plan_name: 'Golden Gate Excursion',
    plan_notes: 'Bring a jacket.',
    activities: [
      'Golden Gate Bridge',
      'Alcatraz Island',
      "Fisherman's Wharf",
      'Cable Car Ride',
      'Chinatown',
      'Lombard Street',
      'Muir Woods',
      'Exploratorium',
      'San Francisco Museum of Modern Art',
      'Union Square',
      'Coit Tower',
      'Palace of Fine Arts',
    ],
  },
];

const sData = [
  'Tiny Museum',
  'Flooded ponds',
  'fast food',
  'Depressing Tree-less park',
  'French Quarter',
  'Live jazz',
  'Jackson Square',
  'Creole Cuisine',
  'Broadway',
  'Central Park',
  'Times Square',
  'Statue of Liberty',
  'Casinos',
  'Shows',
  'The Strip',
  'Helicopter Tour',
  'Bellagio Fountains',
  'Red Rock Canyon',
  'South Beach',
  'Art Deco District',
  'Ocean Drive',
  'Boat Tour',
  'Little Havana',
  'Wynwood Walls',
  'Vizcaya Museum and Gardens',
  'Miami Seaquarium',
  'Golden Gate Bridge',
  'Alcatraz Island',
  "Fisherman's Wharf",
  'Cable Car Ride',
  'Chinatown',
  'Lombard Street',
  'Muir Woods',
  'Exploratorium',
  'San Francisco Museum of Modern Art',
  'Union Square',
  'Coit Tower',
  'Palace of Fine Arts',
];

module.exports = {
  pData,
  sData,
};
